class TradeExitReason:
    SL_HIT = 'SL_HIT'
    TRAIL_SL_HIT = 'TRAIL_SL_HIT'
    TARGET_HIT = 'TARGET_HIT'
    SQUARE_OFF = 'SQUARE_OFF'
    SL_CANCELLED = 'SL_CANCELLED'
    TARGET_CANCELLED = 'TARGET CANCELLED'
    MAX_LOSS = 'MAX LOSS'
